#macro NN_DISCONNECT 0
#macro NN_LBY_CONNECTED 1
#macro NN_CHAT 2
#macro NN_LBY_REQUEST_SETTINGS 3
#macro NN_LBY_SEND_SETTINGS 4
#macro NN_LBY_PRESS_BEJ3 5
#macro NN_LBY_PRESS_CLASSIC 6
#macro NN_LBY_SKINS 7
#macro NN_LBY_TWIST 8
#macro NN_LBY_MATCHLESS 9
#macro NN_LBY_HYPERCUBES 10
#macro NN_LBY_MULTISWAP 11
#macro NN_LBY_GAMEMODE 12
#macro NN_LBY_GAMEMODE2 13
#macro NN_LBY_READY 14
#macro NN_MATCH_BOARD_SPAWN 15
#macro NN_MATCH_GEM_DEATH 16
#macro NN_MATCH_GEM_SPAWN 17
#macro NN_MATCH_GEM_SWAP 18
#macro NN_MATCH_DUALHYPE_MAKE_HYPE 19 //when a dual hype has happened, spawner will spawn a specific array of gems. Two will be hypes.
#macro NN_MATCH_GEM_POWER 20
#macro NN_MATCH_GEM_POWER_NEW 21
#macro NN_BACK_TO_LOBBY 22
#macro NN_MATCH_GEM_COMBO_SOUND 23
#macro NN_MATCH_BLAZING_SPEED_ON 24
#macro NN_MATCH_BLAZING_SPEED_OFF 25
#macro NN_POINTS_ADD 26
#macro NN_STYLE_ADD 27
#macro NN_MATCH_GEM_HYPER 28
#macro NN_MATCH_GEM_HYPER_NEW 29
#macro NN_MATCH_HYPE_SWAP 30
#macro NN_MATCH_HYPE_OFF 31
#macro NN_MATCH_GO 32
#macro NN_MATCH_TWIST_SWAP 33
#macro NN_MATCH_TIMEUP 34
#macro NN_MATCH_AHM_SPAWN 35
#macro NN_MATCH_AHM_SETSKIN 36
#macro NN_MATCH_AVALANCHE_END_TURN 37
#macro NN_MATCH_AVALANCHE_HIDDENMINUS 38 //subtract minus gems by spawning a gem
#macro NN_MATCH_AVALANCHE_GAMEOVER 39
#macro NN_MUSIC_DANGERON 40
#macro NN_MUSIC_DANGEROFF 41
#macro NN_MATCH_AVALANCHE_MAKE_INVGEMS 42
#macro NN_MATCH_AVALANCHE_DESTROY_INVGEMS 43
#macro NN_LBY_DEFENSE 44
#macro NN_MATCH_AVALANCHE_PASS 45
#macro NN_LBY_ULTRANOVAS 46




